grpc:
    server:
        port: 9090

server:
    port: 8080

spring:
    application:
        name: 'oapenwb-spring'
    datasource:
        url: jdbc:postgresql://host:port/database_name
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    liquibase:
        enabled: false
