#!/bin/bash
set -e

POSTGRES="psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}"

echo "Creating database roles: ${APP_USER}, ${TEST_USER}"

$POSTGRES <<-EOSQL
  CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};

  CREATE USER ${TEST_USER} WITH PASSWORD '${TEST_PASSWORD}';
  CREATE DATABASE ${TEST_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${TEST_DB} TO ${TEST_USER};
EOSQL
